### PR TITLE
Adding languages and countries

### PR DESCRIPTION
**Pull request by TrifanBogdan24**
Respecting international abbreviations form https://www.iban.com/country-codes, I extended the enums

### CODE REVIEW

**Comment by TrifanBogdan24** [comment]
Solved issues: 
- Enumerate Languages And Dialect Regions #79
- Language Handling #60

**Comment by TrifanBogdan24** [comment]
for language and region detection functions for Unix systems: Improved Language Detection #55

**Review by alexandruradovici — CHANGES_REQUESTED** [review]
Remove the `.idea` folder from the repository.

**Comment by TrifanBogdan24** [comment]
I recieved feedback from [AldaronLau](https://github.com/AldaronLau) here : https://github.com/ardaku/whoami/pull/81

I hope the `.idea` is no longer there.

**Pull request closed without merging**
